# Generated by Django 4.1.6 on 2023-02-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='banner',
        ),
        migrations.AddField(
            model_name='movies',
            name='banner_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movies',
            name='banner_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movies',
            name='banner_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movies',
            name='banner_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
