# Generated by Django 4.1.6 on 2023-02-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0003_alter_list_mov_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('background', models.ImageField(upload_to='')),
                ('Description', models.TextField(max_length=200)),
                ('About', models.TextField(max_length=500)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebk.list_mov')),
            ],
        ),
    ]
