# Generated by Django 4.1.6 on 2023-02-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0005_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_mov',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='catrogies',
            new_name='name',
        ),
    ]
