# Generated by Django 4.1.6 on 2023-02-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0006_rename_name_list_mov_name_rename_name_main_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
