# Generated by Django 4.1.6 on 2023-02-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0008_alter_movies_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_mov',
            old_name='movies',
            new_name='movie',
        ),
    ]
