# Generated by Django 4.1.6 on 2023-02-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0010_theaters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theaters',
            old_name='time1',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='theaters',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='theaters',
            name='time3',
        ),
        migrations.RemoveField(
            model_name='theaters',
            name='time4',
        ),
    ]
