# Generated by Django 4.1.6 on 2023-02-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0011_rename_time1_theaters_time_remove_theaters_time2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theaters',
            old_name='time',
            new_name='time_1',
        ),
        migrations.AddField(
            model_name='theaters',
            name='time_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='theaters',
            name='time_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='theaters',
            name='time_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
