# Generated by Django 4.1.6 on 2023-02-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0012_rename_time_theaters_time_1_theaters_time_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cast_crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cast', 'cast'), ('crew', 'crew')], max_length=200)),
                ('profile', models.ImageField(upload_to='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebk.main')),
            ],
        ),
    ]
