# Generated by Django 4.1.6 on 2023-02-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0013_cast_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theaters',
            name='time_1',
        ),
        migrations.RemoveField(
            model_name='theaters',
            name='time_2',
        ),
        migrations.RemoveField(
            model_name='theaters',
            name='time_3',
        ),
        migrations.RemoveField(
            model_name='theaters',
            name='time_4',
        ),
        migrations.AddField(
            model_name='theaters',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='date_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebk.main')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebk.theaters')),
            ],
        ),
    ]
