# Generated by Django 4.1.6 on 2023-02-22 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0014_remove_theaters_time_1_remove_theaters_time_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='theaters',
            name='location',
        ),
        migrations.RemoveField(
            model_name='theaters',
            name='theater_name',
        ),
        migrations.AddField(
            model_name='theaters',
            name='theater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moviebk.theater'),
            preserve_default=False,
        ),
    ]
