# Generated by Django 4.1.6 on 2023-02-22 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0015_theater_remove_theaters_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_time',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebk.theater'),
        ),
    ]
