# Generated by Django 4.1.6 on 2023-02-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0017_rename_theater_date_time_theater_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_time',
            old_name='theater_name',
            new_name='theater',
        ),
    ]
