# Generated by Django 4.1.6 on 2023-02-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0018_rename_theater_name_date_time_theater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_time',
            old_name='theater',
            new_name='theater_name',
        ),
    ]
