# Generated by Django 4.1.6 on 2023-02-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0019_rename_theater_date_time_theater_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theaters',
            old_name='theater',
            new_name='theater_name',
        ),
    ]
