# Generated by Django 4.1.6 on 2023-02-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0020_rename_theater_theaters_theater_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.PositiveSmallIntegerField()),
                ('col_num', models.PositiveSmallIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebk.main')),
                ('theater_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebk.theater')),
            ],
        ),
    ]
