# Generated by Django 4.1.6 on 2023-02-23 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0021_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('no_of_rows', models.IntegerField(validators=[django.core.validators.MaxValueValidator(75)])),
                ('no_of_columns', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
            ],
        ),
    ]
