# Generated by Django 4.1.6 on 2023-02-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0022_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='theatre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='screen', to='moviebk.theater'),
            preserve_default=False,
        ),
    ]
