# Generated by Django 4.1.6 on 2023-02-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0024_remove_screen_theatre_delete_booking_delete_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('row_num', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
