# Generated by Django 4.1.6 on 2023-02-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebk', '0025_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='seat_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
